# syntax=docker/dockerfile:1
FROM python:3.10-alpine
# легковесный линукс с питоном

WORKDIR /code

# переменные окружения
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
# ставим зависимости

EXPOSE 5000 
# заметка для админа, какой порт потом надо публиковать
COPY app.py .
# копируем из текущего каталога в workdir

CMD ["flask", "run", "--debug"]
# запускаем flask